DELETE http://localhost:3001/api/todos/60d003bc0132cf30855d4273
#
POST http://localhost:3001/api/todos
Content-Type: application/json
{
"content": "Vacuum the living room",
"completed": "false"
}
#
POST http://localhost:3001/api/todos
Content-Type: application/json
{
"content": "Plan my monthly budget",
"completed": "false"
}
#
GET http://localhost:3001/api/todos/60d003bc0132cf30855d4273
